spree_glabs_vintage_theme_1/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :spree do
    namespace :spree_vintage_theme do
      resources :theme_colors
      resources :theme_images
    end
  end

  scope :module => 'spree_vintage_theme' do
    resources :infos
    match "order_information" => "infos#order_information", :via => :get, :as => "order_information"
    match "search_order" => "infos#search_order", :via => :post, :as => "search_order"
  end

  namespace :admin do
    namespace :spree_vintage_theme do
      resources :theme_images
      resources :theme_colors
      resources :infos
    end
  end

  namespace :admin, :scope => "spree_vintage_theme/theme_colors" do
    match "edit_theme" => "spree_vintage_theme/theme_colors#edit_theme", :via => :post, :as => "edit_theme"
    match "update_theme" => "spree_vintage_theme/theme_colors#update_theme", :via => :post, :as => "update_theme"
  end

  namespace :admin, :scope => "spree_vintage_theme/theme_images" do
    match "enabled_selected" => "spree_vintage_theme/theme_images#enabled_selected", :via => :post, :as => "enabled_selected"
    match "redirect_enabled_selected" => "spree_vintage_theme/theme_images#redirect_enabled_selected", :via => :get, :as => "redirect_enabled"
  end

  get "/best_seller/" => "products#best_product"
  get "/new/" => "products#newest_product"
  get "/promo/" => "products#promotion_product"

  match "locale/change" => "locale#change_locale", :as => "change_locale"
end

spree_glabs_vintage_theme_1/app/models/spree/admin/spree_vintage_theme.rb
module Spree::Admin::SpreeVintageTheme
  def self.table_name_prefix
    'spree_admin_spree_vintage_theme_'
  end
end

spree_glabs_vintage_theme_1/app/models/spree/spree_vintage_theme.rb
module Spree::SpreeVintageTheme
  def self.table_name_prefix
    'spree_spree_vintage_theme_'
  end
end

spree_glabs_vintage_theme_1/app/models/spree/spree_vintage_theme/info.rb
class Spree::SpreeVintageTheme::Info < ActiveRecord::Base
  attr_accessible :body, :title
end

spree_glabs_vintage_theme_1/app/models/spree/spree_vintage_theme/theme_color.rb
class Spree::SpreeVintageTheme::ThemeColor < ActiveRecord::Base
  self.table_name = 'spree_spree_vintage_theme_theme_colors'
  attr_accessible :color, :filename, :used
end

spree_glabs_vintage_theme_1/app/models/spree/spree_vintage_theme/theme_image.rb
class Spree::SpreeVintageTheme::ThemeImage < ActiveRecord::Base
  self.table_name = 'spree_spree_vintage_theme_theme_images'
  attr_accessible :description, :enabled, :image, :url_destination

  has_attached_file :image, :styles => { :small => "200x200>", :thumb => "100x100>", :banner => "1014X500>" }
  # validate :file_dimensions, :unless => "errors.any?", :on => :create

  def file_dimensions
    dimensions = Paperclip::Geometry.from_file(image.queued_for_write[:original].path)
    # width  : 1024px
    # height : 510px
    if dimensions.width < 974 || dimensions.width > 1700
      errors.add(:file, (I18n.t "messages.theme_images.range_width", :range_1 => "974", :range_2 => "1700"))
    end

    if dimensions.height < 460 || dimensions.height > 1100
      errors.add(:file, (I18n.t "messages.theme_images.range_height", :range_1 => "460", :range_2 => "510"))
    end
  end
end

spree_glabs_vintage_theme_1/app/controllers/spree/admin/spree_vintage_theme/infos_controller.rb
class Spree::Admin::SpreeVintageTheme::InfosController < Spree::Admin::BaseController
  def index
    @infos = Spree::SpreeVintageTheme::Info.all
  end

  def edit
    @info = Spree::SpreeVintageTheme::Info.find(params[:id])
  end

  def update
    @info = Spree::SpreeVintageTheme::Info.find(params[:id])
    if @info.update_attributes(params[:spree_vintage_theme_info])
      redirect_to admin_spree_vintage_theme_infos_path, :notice => "#{t("fat_footer.#{@info.title}")} #{t(:updated)}"
    else
      render action: "edit", :error => @info.errors
    end
  end
end

spree_glabs_vintage_theme_1/app/controllers/spree/admin/spree_vintage_theme/theme_colors_controller.rb
module Spree
  module Admin
    class SpreeVintageTheme::ThemeColorsController < Spree::Admin::BaseController
      include Spree::Admin::SpreeVintageTheme::ThemeColorsHelper

      def update_theme
        @old_theme = Spree::SpreeVintageTheme::ThemeColor.where(:used => "true").first
        @new_theme = Spree::SpreeVintageTheme::ThemeColor.find(params[:theme_color])
        @new_theme.used = "true"

        unless @old_theme.nil?
          @old_theme.used = "false"
          if @old_theme.save && @new_theme.save
            change_color(@old_theme, @new_theme)
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.succeed")
          else
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.failed")
          end
        else
          if @new_theme.save
            change_color(@old_theme, @new_theme)
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.succeed")
          else
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.failed")
          end
        end
      end
    end
  end
end

spree_glabs_vintage_theme_1/app/controllers/spree/admin/spree_vintage_theme/theme_images_controller.rb
module Spree
  module Admin
    module SpreeVintageTheme
      class ThemeImagesController < Spree::Admin::BaseController
        def index
          @images = Spree::SpreeVintageTheme::ThemeImage.all
          @image = Spree::SpreeVintageTheme::ThemeImage.new
          @theme_color = Spree::SpreeVintageTheme::ThemeColor.where(:used => "true").first
          @theme_colors = Spree::SpreeVintageTheme::ThemeColor.find(:all, :order => "used DESC")
        end

        def new
          @image = Spree::SpreeVintageTheme::ThemeImage.new
        end

        def create
          @images = params[:spree_vintage_theme_theme_image][:image]
          if @images.count > 1 # NOTE for multiple upload
            @index = 0
            @images.each do |image|
              @image = Spree::SpreeVintageTheme::ThemeImage.create(:image => params[:spree_vintage_theme_theme_image][:image][@index])
              if @image.new_record?
                @error = true
              else
                @error = false
              end
              @index += 1
            end

            if @error == true
              redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => @image.errors.messages[:file]
            else
              redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.theme_images.succeed_add")
            end
          else
            @image = Spree::SpreeVintageTheme::ThemeImage.create(:image => params[:spree_vintage_theme_theme_image][:image][0])
            if @image.new_record?
              redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => @image.errors.messages[:file]
            else
              redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.theme_images.succeed_add")
            end
          end
        end

        def edit
          @image = Spree::SpreeVintageTheme::ThemeImage.find(params[:id])
        end

        def update
          @image = Spree::SpreeVintageTheme::ThemeImage.find(params[:id])
          if @image.update_attributes(params[:spree_vintage_theme_theme_image])
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, notice: (I18n.t "messages.theme_images.succeed_edit")
          else
            render action: "edit", :error => @image.errors
          end
        end

        def destroy
          @image = Spree::SpreeVintageTheme::ThemeImage.find(params[:id])
          if @image.destroy
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.theme_images.succeed_destroy")
          else
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => @image.errors
          end
        end

        def enabled_selected
          @arr_images = params[:arr_images]
          @arr_images_o = Spree::SpreeVintageTheme::ThemeImage.where(:enabled => "true")
          @arr_images_o.each do |image|
            image.enabled = "false"
            image.save
          end

          @arr_images.each do |image|
            @data = Spree::SpreeVintageTheme::ThemeImage.find(image)
            @data.enabled = "true"

            if @data.save
              @notice = "s"
            else
              @notice = "f"
            end
          end

          respond_to do |format|
            format.json { render :json => {:notice => @notice} }
          end
        end

        def redirect_enabled_selected
          if params[:notice] == "s"
            @notice = I18n.t "messages.succeed"
          else
            @notice = I18n.t "messages.failed"
          end

          redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => @notice
        end
      end
    end
  end
end

spree_glabs_vintage_theme_1/app/controllers/spree/spree_vintage_theme/infos_controller.rb
class Spree::SpreeVintageTheme::InfosController < Spree::BaseController
  helper "Spree::Products"
  include Spree::SpreeVintageTheme::InfosHelper
  before_filter :new_variable

  def new_variable
    load_new_variable
  end

  def show
    @info = Spree::SpreeVintageTheme::Info.find(params[:id])
  end

  def order_information
    @order = Spree::Order.new
  end

  def search_order
    @order = Spree::Order.find_by_number(params[:order][:number])
    @customer = "#{@order.bill_address.firstname} #{@order.bill_address.lastname}" unless @order.nil?
    respond_to do |format|
      format.js
    end
  end
end

spree_glabs_vintage_theme_1/app/helpers/spree/admin/spree_vintage_theme/infos_helper.rb
module Spree::Admin::SpreeVintageTheme::InfosHelper
end

spree_glabs_vintage_theme_1/app/helpers/spree/admin/spree_vintage_theme/theme_colors_helper.rb
module Spree::Admin::SpreeVintageTheme::ThemeColorsHelper
  def change_color(old_theme, new_theme)
    @file = File.readlines('./app/assets/stylesheets/store/all.css')
    index = 0
    find = false

    unless old_theme.nil?
      @file.each do |f|
        if f.include?(old_theme.filename)
          find = true
          break
        end
        index += 1
      end
    end
    @file.delete_at(index) if find
    index = @file.count - 2 if index == 0
    @file.insert(index, " *= require store/spree_vintage_theme/#{new_theme.filename}\n")
    File.open('./app/assets/stylesheets/store/all.css', 'w+') { |f| f.write @file.join() }
  end
end

spree_glabs_vintage_theme_1/app/helpers/spree/admin/spree_vintage_theme/theme_images_helper.rb
module Spree::Admin::SpreeVintageTheme::ThemeImagesHelper
end

spree_glabs_vintage_theme_1/app/helpers/spree/spree_vintage_theme/infos_helper.rb
module Spree::SpreeVintageTheme::InfosHelper
  def load_new_variable
    @contact_us = Spree::SpreeVintageTheme::Info.find_by_title("contact_us")
    @how_to_shop = Spree::SpreeVintageTheme::Info.find_by_title("how_to_shop")
    @confirm_transfer = Spree::SpreeVintageTheme::Info.find_by_title("confirm_transfer")
  end

  def check_locales(locale)
    find = false
    I18n.available_locales.each do |l|
      if locale.to_s == l.to_s
        find = true
        break
      end
    end
    return find
  end
end

spree_glabs_vintage_theme_1/app/views/spree/shared/_fat_footer.html.erb
<script style="text/javascript">
  $(document).ready(function(){
    $("nav#taxonomies").addClass("taxon-fat-footer");
    <% if current_page?(root_path) %>
      $("#sidebar").remove();
    <% end %>
  });
</script>

<div style="clear:both"></div>
<div id="fat-footer">
  <% get_taxonomies.each do |taxonomy| %>
    <div class="fat-footer-taxon">
      <h6 class='taxonomy-root'><%= taxonomy.name %></h6>
      <%= taxons_tree(taxonomy.root, @taxon, Spree::Config[:max_level_in_taxons_menu] || 1) %>
    </div>
  <% end %>
  <div class="fat-footer-taxon">
    <h6 class='taxonomy-root'><%= t :service %></h6>
      <ul class="taxons-list">
        <li>
          <% unless @contact_us.nil? %>
            <%= link_to (t "fat_footer.contact_us"), info_path(@contact_us) %>
          <% else %>
            <%= link_to (t "fat_footer.contact_us"), "#" %>
          <% end %>
        </li>
        <li>
          <% unless @how_to_shop.nil? %>
            <%= link_to (t "fat_footer.how_to_shop"), info_path(@how_to_shop) %>
          <% else %>
            <%= link_to (t "fat_footer.how_to_shop"), "#" %>
          <% end %>
        </li>
        <% if !@confirm_transfer.nil? %>
          <li><%= link_to (t "fat_footer.confirm_transfer"), info_path(@confirm_transfer) %></li>
        <% end %>
        <li><%= link_to (t "fat_footer.order_information"), order_information_path %></li>
      </ul>
  </div>
</div>

spree_glabs_vintage_theme_1/app/views/spree/shared/_footer_company_name.html.erb
<!--<div id="company_name_footer">Powered by Garasilabs</div>-->
<style type="text/css">
  footer#footer{
    border-top:0px !important;
  }
</style>

spree_glabs_vintage_theme_1/app/views/spree/shared/_header.html.erb
<div id="header">
  <div class="line_header">
  </div>
	<div class="headline_right">
		<div class="account_locale_cart">
      <ul class="kotak_cart">
        <li><%= link_to "#{t :cart}", cart_path %></li>
        <li class="value_cart"><%= @current_order_user.nil? ? "0" : @current_order_user.display_total %></li>
      </ul>
      <ul class="search">
        <%= form_tag products_path, :method => :get, :id => "form_search" do %>
          <li class="img_search">
            <%= image_submit_tag "store/spree_vintage_theme/default/Search.png", :name => nil, :id => "btn_search" %>
          </li>
          <li>
            <%= search_field_tag :keywords, params[:keywords], :placeholder => t(:search) %> 
          </li>
        <% end %>
      </ul>
      <% if current_user.nil? %>
        <%= render :partial => "shared/login.html.erb" %>
      <% else %>
        <%= render :partial => "shared/logout.html.erb" %>
      <% end %>
		</div>
	</div>
	<div class="headline_left">
		<div class="logo">
			<%= link_to image_tag('store/spree_vintage_theme/default/logo coba.png'), root_path %>
		</div>
		<div class="menu">
			<ul class="navigation_menu">
        <% @menus.each do |taxon| %>
          <li><%= link_to(taxon.name, seo_url(taxon)) %></li>
        <% end %>
        <li><a href="#" id="more_menu" data-toggle="modal"><%= t :more %></a></li>
			</ul>
		</div>
</div>

<div class="notice">
</div>
<div class="error">
</div>
<div id="dlg_more_menu" title="<%= t :more_menu %>">
  <h3 id="myModalLabel">More menu</h3>
  <% get_taxonomies.each do |taxonomy| %>
    <div class="fat-footer-taxon">
    <h6 class='taxonomy-root'><%= taxonomy.name %></h6>
    <%= taxons_tree(taxonomy.root, @taxon, Spree::Config[:max_level_in_taxons_menu] || 1) %>
    </div>
  <% end %>
</div>

<style type="text/css">
  #dlg_more_menu .close{
    color: black;
  }
</style>

<script type="text/javascript">
  $(document).ready(function(){
    $("#locale").change(function(){
      $.ajax({
                url: "<%= change_locale_path %>",
                type: "POST",
                data: { locale: $("#locale").val() },
                success: function(result)
                         {
                            if(result.notice != "")
                              location.reload();
                            else
                              alert(result.error);
                         }
      });
    });
  });
</script>

spree_glabs_vintage_theme_1/app/views/spree/shared/_insert_forgot_password.html.erb
<%= link_to t(:forgot_password), spree.new_user_password_path, :id => "forgot_password_link" %>

spree_glabs_vintage_theme_1/app/views/spree/shared/_new_product_info.html.erb
<span class="product_name"><%= product.name %></span>
<div class="product-info">
  <span class="product_price"><%= link_to t(:view), product_path(product), :itemprop => 'url', :class => 'product_view' %></span>
</div>

<script type="text/javascript">
  $(document).ready(function(){
      $("a.info").remove();

      $(".product-info").hide();

      $(".product-image img").mouseover(function(){
        $(this).parent().parent().parent().find(".product-info").show();
      });

      $(".product-info").mouseover(function(){
        $(this).show();
      });

      $(".product-image img").mouseout(function(){
         $(this).parent().parent().parent().find(".product-info").hide();
      });

      $(".product-info").mouseover(function(){
        $(this).show();
      });

      $(".product-info").mouseout(function(){
        $(this).hide();
      });
  });
</script>