spree_glabs_vintage_theme_1/config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :spree do
    namespace :spree_vintage_theme do
      resources :theme_colors
      resources :theme_images
    end
  end

  scope :module => 'spree_vintage_theme' do
    resources :infos
    match "order_information" => "infos#order_information", :via => :get, :as => "order_information"
    match "search_order" => "infos#search_order", :via => :post, :as => "search_order"
  end

  namespace :admin do
    namespace :spree_vintage_theme do
      resources :theme_images
      resources :theme_colors
      resources :infos
    end
  end

  namespace :admin, :scope => "spree_vintage_theme/theme_colors" do
    match "edit_theme" => "spree_vintage_theme/theme_colors#edit_theme", :via => :post, :as => "edit_theme"
    match "update_theme" => "spree_vintage_theme/theme_colors#update_theme", :via => :post, :as => "update_theme"
  end

  namespace :admin, :scope => "spree_vintage_theme/theme_images" do
    match "enabled_selected" => "spree_vintage_theme/theme_images#enabled_selected", :via => :post, :as => "enabled_selected"
    match "redirect_enabled_selected" => "spree_vintage_theme/theme_images#redirect_enabled_selected", :via => :get, :as => "redirect_enabled"
  end

  get "/best_seller/" => "products#best_product"
  get "/new/" => "products#newest_product"
  get "/promo/" => "products#promotion_product"

  match "locale/change" => "locale#change_locale", :as => "change_locale"
end

spree_glabs_vintage_theme_1/app/models/admin/spree_vintage_theme.rb
module Admin::SpreeVintageTheme
  def self.table_name_prefix
    'admin_spree_vintage_theme_'
  end
end

spree_glabs_vintage_theme_1/app/models/spree/admin/spree_vintage_theme.rb
module Spree::Admin::SpreeVintageTheme
  def self.table_name_prefix
    'spree_admin_spree_vintage_theme_'
  end
end

spree_glabs_vintage_theme_1/app/models/spree/spree_vintage_theme.rb
module Spree::SpreeVintageTheme
  def self.table_name_prefix
    'spree_spree_vintage_theme_'
  end
end

spree_glabs_vintage_theme_1/app/models/spree/spree_vintage_theme/info.rb
class Spree::SpreeVintageTheme::Info < ActiveRecord::Base
  attr_accessible :body, :title
end

spree_glabs_vintage_theme_1/app/models/spree/spree_vintage_theme/theme_color.rb
class Spree::SpreeVintageTheme::ThemeColor < ActiveRecord::Base
  self.table_name = 'spree_spree_vintage_theme_theme_colors'
  attr_accessible :color, :filename, :used
end

spree_glabs_vintage_theme_1/app/models/spree/spree_vintage_theme/theme_image.rb
class Spree::SpreeVintageTheme::ThemeImage < ActiveRecord::Base
  self.table_name = 'spree_spree_vintage_theme_theme_images'
  attr_accessible :description, :enabled, :image, :url_destination

  has_attached_file :image, :styles => { :small => "200x200>", :thumb => "100x100>", :banner => "1014X500>" }
  # validate :file_dimensions, :unless => "errors.any?", :on => :create

  def file_dimensions
    dimensions = Paperclip::Geometry.from_file(image.queued_for_write[:original].path)
    # width  : 1024px
    # height : 510px
    if dimensions.width < 974 || dimensions.width > 1700
      errors.add(:file, (I18n.t "messages.theme_images.range_width", :range_1 => "974", :range_2 => "1700"))
    end

    if dimensions.height < 460 || dimensions.height > 1100
      errors.add(:file, (I18n.t "messages.theme_images.range_height", :range_1 => "460", :range_2 => "510"))
    end
  end
end

spree_glabs_vintage_theme_1/app/controllers/spree/admin/spree_vintage_theme/infos_controller.rb
class Spree::Admin::SpreeVintageTheme::InfosController < Spree::Admin::BaseController
  def index
    @infos = Spree::SpreeVintageTheme::Info.all
  end

  def edit
    @info = Spree::SpreeVintageTheme::Info.find(params[:id])
  end

  def update
    @info = Spree::SpreeVintageTheme::Info.find(params[:id])
    if @info.update_attributes(params[:spree_vintage_theme_info])
      redirect_to admin_spree_vintage_theme_infos_path, :notice => "#{t("fat_footer.#{@info.title}")} #{t(:updated)}"
    else
      render action: "edit", :error => @info.errors
    end
  end
end

spree_glabs_vintage_theme_1/app/controllers/spree/admin/spree_vintage_theme/theme_colors_controller.rb
module Spree
  module Admin
    class SpreeVintageTheme::ThemeColorsController < Spree::Admin::BaseController
      include Spree::Admin::SpreeVintageTheme::ThemeColorsHelper

      def update_theme
        @old_theme = Spree::SpreeVintageTheme::ThemeColor.where(:used => "true").first
        @new_theme = Spree::SpreeVintageTheme::ThemeColor.find(params[:theme_color])
        @new_theme.used = "true"

        unless @old_theme.nil?
          @old_theme.used = "false"
          if @old_theme.save && @new_theme.save
            change_color(@old_theme, @new_theme)
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.succeed")
          else
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.failed")
          end
        else
          if @new_theme.save
            change_color(@old_theme, @new_theme)
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.succeed")
          else
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.failed")
          end
        end
      end
    end
  end
end

spree_glabs_vintage_theme_1/app/controllers/spree/admin/spree_vintage_theme/theme_images_controller.rb
module Spree
  module Admin
    module SpreeVintageTheme
      class ThemeImagesController < Spree::Admin::BaseController
        def index
          @images = Spree::SpreeVintageTheme::ThemeImage.all
          @image = Spree::SpreeVintageTheme::ThemeImage.new
          @theme_color = Spree::SpreeVintageTheme::ThemeColor.where(:used => "true").first
          @theme_colors = Spree::SpreeVintageTheme::ThemeColor.find(:all, :order => "used DESC")
        end

        def new
          @image = Spree::SpreeVintageTheme::ThemeImage.new
        end

        def create
          @images = params[:spree_vintage_theme_theme_image][:image]
          if @images.count > 1 # NOTE for multiple upload
            @index = 0
            @images.each do |image|
              @image = Spree::SpreeVintageTheme::ThemeImage.create(:image => params[:spree_vintage_theme_theme_image][:image][@index])
              if @image.new_record?
                @error = true
              else
                @error = false
              end
              @index += 1
            end

            if @error == true
              redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => @image.errors.messages[:file]
            else
              redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.theme_images.succeed_add")
            end
          else
            @image = Spree::SpreeVintageTheme::ThemeImage.create(:image => params[:spree_vintage_theme_theme_image][:image][0])
            if @image.new_record?
              redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => @image.errors.messages[:file]
            else
              redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.theme_images.succeed_add")
            end
          end
        end

        def edit
          @image = Spree::SpreeVintageTheme::ThemeImage.find(params[:id])
        end

        def update
          @image = Spree::SpreeVintageTheme::ThemeImage.find(params[:id])
          if @image.update_attributes(params[:spree_vintage_theme_theme_image])
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, notice: (I18n.t "messages.theme_images.succeed_edit")
          else
            render action: "edit", :error => @image.errors
          end
        end

        def destroy
          @image = Spree::SpreeVintageTheme::ThemeImage.find(params[:id])
          if @image.destroy
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => (I18n.t "messages.theme_images.succeed_destroy")
          else
            redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => @image.errors
          end
        end

        def enabled_selected
          @arr_images = params[:arr_images]
          @arr_images_o = Spree::SpreeVintageTheme::ThemeImage.where(:enabled => "true")
          @arr_images_o.each do |image|
            image.enabled = "false"
            image.save
          end

          @arr_images.each do |image|
            @data = Spree::SpreeVintageTheme::ThemeImage.find(image)
            @data.enabled = "true"

            if @data.save
              @notice = "s"
            else
              @notice = "f"
            end
          end

          respond_to do |format|
            format.json { render :json => {:notice => @notice} }
          end
        end

        def redirect_enabled_selected
          if params[:notice] == "s"
            @notice = I18n.t "messages.succeed"
          else
            @notice = I18n.t "messages.failed"
          end

          redirect_to spree.admin_spree_vintage_theme_theme_images_path, :notice => @notice
        end
      end
    end
  end
end

spree_glabs_vintage_theme_1/app/controllers/spree/spree_vintage_theme/infos_controller.rb
class Spree::SpreeVintageTheme::InfosController < Spree::BaseController
  helper "Spree::Products"
  include Spree::SpreeVintageTheme::InfosHelper
  before_filter :new_variable

  def new_variable
    load_new_variable
  end

  def show
    @info = Spree::SpreeVintageTheme::Info.find(params[:id])
  end

  def order_information
    @order = Spree::Order.new
  end

  def search_order
    @order = Spree::Order.find_by_number(params[:order][:number])
    @customer = "#{@order.bill_address.firstname} #{@order.bill_address.lastname}" unless @order.nil?
    respond_to do |format|
      format.js
    end
  end
end

spree_glabs_vintage_theme_1/app/helpers/spree/admin/spree_vintage_theme/infos_helper.rb
module Spree::Admin::SpreeVintageTheme::InfosHelper
end

spree_glabs_vintage_theme_1/app/helpers/spree/admin/spree_vintage_theme/theme_colors_helper.rb
module Spree::Admin::SpreeVintageTheme::ThemeColorsHelper
  def change_color(old_theme, new_theme)
    @file = File.readlines('./app/assets/stylesheets/store/all.css')
    index = 0
    find = false

    unless old_theme.nil?
      @file.each do |f|
        if f.include?(old_theme.filename)
          find = true
          break
        end
        index += 1
      end
    end
    @file.delete_at(index) if find
    index = @file.count - 2 if index == 0
    @file.insert(index, " *= require store/spree_vintage_theme/#{new_theme.filename}\n")
    File.open('./app/assets/stylesheets/store/all.css', 'w+') { |f| f.write @file.join() }
  end
end

spree_glabs_vintage_theme_1/app/helpers/spree/admin/spree_vintage_theme/theme_images_helper.rb
module Spree::Admin::SpreeVintageTheme::ThemeImagesHelper
end

spree_glabs_vintage_theme_1/app/helpers/spree/spree_vintage_theme/infos_helper.rb
module Spree::SpreeVintageTheme::InfosHelper
  def load_new_variable
    @contact_us = Spree::SpreeVintageTheme::Info.find_by_title("contact_us")
    @how_to_shop = Spree::SpreeVintageTheme::Info.find_by_title("how_to_shop")
    @confirm_transfer = Spree::SpreeVintageTheme::Info.find_by_title("confirm_transfer")
  end

  def check_locales(locale)
    find = false
    I18n.available_locales.each do |l|
      if locale.to_s == l.to_s
        find = true
        break
      end
    end
    return find
  end
end

spree_glabs_vintage_theme_1/app/views/spree/admin/spree_vintage_theme/theme_images/_form.html.erb
<%= form_for @image, :url => spree.admin_spree_vintage_theme_theme_images_path do |f| %>
  <table>
    <tr>
      <td><%= t :filename %></td>
      <td><%= f.file_field :image, :multiple => true %></td>
    </tr>
    <tr><td colspan="2"><%= f.submit %></td></tr>
  </table>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
      $(".new_spree_vintage_theme_theme_image input[type='submit']").click(function(e){
        if($("#spree_vintage_theme_theme_image_image").val())
        { }
        else
          e.preventDefault();
      });
  });
</script>

spree_glabs_vintage_theme_1/app/views/spree/admin/spree_vintage_theme/theme_images/edit.html.erb
<%= form_for @image, :url => admin_spree_vintage_theme_theme_image_path do |f| %>
  <table style="width: 60%">
    <tr>
      <td colspan="2"><%= image_tag @image.image.url(:small) %></td>
    </tr>
    <tr>
      <td><%= f.label :description %></td>
      <td><%= f.text_field :description %></td>
    </tr>
    <tr>
      <td><%= f.label :url_destination %></td>
      <td><%= f.text_field :url_destination %></td>
    </tr>
    <tr><td colspan="2"><%= f.submit %></td></tr>
  </table>
<% end %>

spree_glabs_vintage_theme_1/app/views/spree/admin/spree_vintage_theme/theme_images/index.html.erb
<% if !@theme_colors.nil? && !@theme_colors.empty? %>
<div id="theme_color">
  <%= t "activerecord.models.theme_color" %> : <%= !@theme_color.nil? ? @theme_color.color : "-" %>
  <%= button_to (t :edit), spree.admin_edit_theme_path, :method => :get, :id => "btn_edit_theme_color" %>
</div>
<% end %>

<div id="link_new_image" class="link_hover" style="margin-top:1em;"><%= t "theme_image.new_image" %></div>
<% if @images.count > 0 %>
  <table style="width: 50%; margin-top: 1.5em;" class=" index responsive">
    <thead>
    <tr>
      <th width="40%"><%= t "helpers.label.theme_image.image" %></th>
      <th><%= t "helpers.label.theme_image.description" %></th>
      <th><%= t "theme_image.destination" %></th>
      <th><%= t "theme_image.display" %></th>
      <th><%= t :edit %></th>
      <th><%= t :delete %></th>
    </tr>
  </thead>
    <% index = 1 %>
    <% @images.each do |image| %>
      <tr>
        <td><%= image_tag image.image.url(:small) %></td>
        <td><%= image.description %></td>
        <td><%= image.url_destination %></td>
        <td>
          <% if image.enabled == "true" %>
            <%= check_box_tag 'enabled_image[]', image.id, :id => "chk_enabled_#{image.id}" %>
          <% else %>
            <%= check_box_tag 'enabled_image[]', image.id, false, :id => "chk_enabled_#{image.id}" %>
          <% end%>
        </td>
        <td><%= button_to (t :edit), spree.edit_admin_spree_vintage_theme_theme_image_path(image.id), :method => :get %></td>
        <td><%= button_to (t :delete), spree.admin_spree_vintage_theme_theme_image_path(:id => image.id), :method => :delete, :class => "btn_delete_image" %></td>
      </tr>
      <% index += 1 %>
    <% end %>
  </table>

  <%= button_tag (t :save), :id => "btn_save" %>
<% else %>
  no images
<% end %>

<div title="<%= t "theme_image.add_new_image" %>" id="dlg_new_image">
  <%= render :partial => "form" %>
</div>

<div title="<%= t "theme_image.edit_theme_color" %>" id="dlg_edit_theme_color">
  <%= render :partial => "spree/admin/spree_vintage_theme/theme_colors/edit_theme" %>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    $("#btn_save").click(function(){
      var arr_bantu = Array();
      $.each($("input:checkbox[name='enabled_image[]']:checked"), function(){
        arr_bantu.push($(this).val());
      });

      if(arr_bantu.length >= 2)
      {
        $.ajax({
          type: "POST",
          url: "<%= spree.admin_enabled_selected_path %>",
          data: { arr_images: arr_bantu },
          success: function(result)
                   {
                   if(result.notice == "s")
                     window.location.replace("<%= spree.admin_redirect_enabled_path(:notice => 's') %>");
                   else
                     window.location.replace("<%= spree.admin_redirect_enabled_path(:notice => 'f') %>");
                   }
        });
      }
      else if(arr_bantu.length == 0)
        alert("<%= t 'theme_image.no_image_selected' %>");
      else
        alert("<%= t 'theme_image.minimal_image' %>");
    });

    $(".btn_delete_image").click(function(e){
      <% if @images.count - 1 == 0 %>
        alert("<%= t 'messages.theme_images.cant_delete_more_photo' %>");
        e.preventDefault();
      <% else %>
        confirm("<%= t 'are_you_sure' %>");
      <% end %>
    });

    $("#btn_edit_theme_color").click(function(e){
        e.preventDefault();
        $("#dlg_edit_theme_color").dialog("open");
    });
  });
</script>